In [22]:
import pandas as pd
import io
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

pd.set_option('display.max_columns', 100)

data = pd.read_csv('data.csv')

In [23]:
data.head()

Ph    EC    OC    OM    N    P    K    Zn   Fe    Cu   Mn  Sand  Silt  \
0  8.31  0.07  0.08  0.13  193  2.9   70  0.56  3.4  0.15  1.8  96.0   1.5   
1  8.36  0.02  0.19  0.32  188  6.4  127  0.50  3.1  0.28  2.3  93.9   1.7   
2  7.82  0.04  0.16  0.27  184  4.2   86  0.62  4.4  0.24  0.7  94.0   1.3   
3  8.08  0.08  0.20  0.34  198  3.6  113  0.58  4.6  0.11  4.2  94.4   1.4   
4  8.20  0.10  0.28  0.48  231  2.7  145  0.34  3.2  0.30  1.6  94.5   1.2   

   Clay  CaCO3  CEC       Output  
0   2.5    0.2  1.9  Non-Fertile  
1   4.4    0.0  1.6  Non-Fertile  
2   4.7    0.0  1.2  Non-Fertile  
3   4.2    0.0  1.7  Non-Fertile  
4   4.3    0.0  2.1  Non-Fertile

In [24]:
def Output(s):
  if s == "Non-Fertile":
    return 0
  elif s== "Fertile":
    return 1
  return 3


data.Output = data.Output.map(Output)

In [25]:
data.head()
# test.isnull().any()

Ph    EC    OC    OM    N    P    K    Zn   Fe    Cu   Mn  Sand  Silt  \
0  8.31  0.07  0.08  0.13  193  2.9   70  0.56  3.4  0.15  1.8  96.0   1.5   
1  8.36  0.02  0.19  0.32  188  6.4  127  0.50  3.1  0.28  2.3  93.9   1.7   
2  7.82  0.04  0.16  0.27  184  4.2   86  0.62  4.4  0.24  0.7  94.0   1.3   
3  8.08  0.08  0.20  0.34  198  3.6  113  0.58  4.6  0.11  4.2  94.4   1.4   
4  8.20  0.10  0.28  0.48  231  2.7  145  0.34  3.2  0.30  1.6  94.5   1.2   

   Clay  CaCO3  CEC  Output  
0   2.5    0.2  1.9       0  
1   4.4    0.0  1.6       0  
2   4.7    0.0  1.2       0  
3   4.2    0.0  1.7       0  
4   4.3    0.0  2.1       0

In [28]:
out_cols = data['Output']
X = data.drop(['Output'],axis=1)
y = out_cols
print X,y

split = int(0.75*data.shape[0])
X_train = X[:split]
Y_train = y[:split]
Y_train = np.asarray(Y_train).flatten()


X_test = X[split:]
Y_test = y[split:]
Y_test = np.asarray(Y_test).flatten()

print X_train.shape
print X_test.shape
print Y_train.shape
print Y_test.shape

      Ph    EC    OC    OM    N     P    K    Zn   Fe    Cu   Mn  Sand  Silt  \
0   8.31  0.07  0.08  0.13  193   2.9   70  0.56  3.4  0.15  1.8  96.0   1.5   
1   8.36  0.02  0.19  0.32  188   6.4  127  0.50  3.1  0.28  2.3  93.9   1.7   
2   7.82  0.04  0.16  0.27  184   4.2   86  0.62  4.4  0.24  0.7  94.0   1.3   
3   8.08  0.08  0.20  0.34  198   3.6  113  0.58  4.6  0.11  4.2  94.4   1.4   
4   8.20  0.10  0.28  0.48  231   2.7  145  0.34  3.2  0.30  1.6  94.5   1.2   
5   8.45  0.07  0.08  0.13  142   9.8  173  0.32  3.0  0.21  2.2  91.8   3.1   
6   8.38  0.10  0.06  0.10  125   7.1  198  0.48  4.2  0.15  3.8  88.8   4.9   
7   8.32  0.06  0.11  0.18  157  10.4  185  0.44  3.7  0.24  1.3  90.7   3.6   
8   8.26  0.11  0.04  0.06  146  12.0  276  0.89  6.1  0.45  4.8  91.2   4.0   
9   7.94  0.09  0.16  0.27  190   7.0  248  0.50  3.4  0.32  3.2  89.7   4.5   
10  8.12  0.14  0.76  1.31  421   4.6  283  0.38  3.7  0.18  0.8  86.0   6.7   
11  8.06  0.17  0.20  0.34  211  18.7  4

In [60]:
for i in range(5):
    print '*'*10,'TESTCASE - ',i,'*'*10

    from sklearn.ensemble import RandomForestClassifier
    print '----- RANDOM FOREST -----'
    rf = RandomForestClassifier(n_estimators=100)
    rf.fit(X_train, Y_train)

    testlabel = rf.predict(X_test)
    print testlabel

    acc= rf.score(X_test,Y_test)
    print "Accuracy: ",acc

    print '#'*50






    from sklearn.neighbors import KNeighborsClassifier
    print '----- KNN -----'
    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(X_train, Y_train) 

    testlabel = knn.predict(X_test)
    print testlabel

    acc= knn.score(X_test,Y_test)
    print "Accuracy: ",acc

    print '#'*50





    from sklearn import tree
    print '----- Decision Trees -----'
    dt = tree.DecisionTreeClassifier()
    dt.fit(X_train, Y_train) 

    testlabel = dt.predict(X_test)
    print testlabel

    acc= dt.score(X_test,Y_test)
    print "Accuracy: ",acc


    print '#'*50
    print
    print
    print





********** TESTCASE -  0 **********
----- RANDOM FOREST -----
[1 0 1 1 1 1 0 0 1 1 1 0 0]
Accuracy:  0.615384615385
##################################################
----- KNN -----
[1 1 1 1 1 1 0 0 0 0 0 0 0]
Accuracy:  0.461538461538
##################################################
----- Decision Trees -----
[1 1 0 0 0 1 0 1 1 1 1 1 1]
Accuracy:  0.692307692308
##################################################



********** TESTCASE -  1 **********
----- RANDOM FOREST -----
[1 1 1 1 1 1 0 0 1 0 0 0 0]
Accuracy:  0.538461538462
##################################################
----- KNN -----
[1 1 1 1 1 1 0 0 0 0 0 0 0]
Accuracy:  0.461538461538
##################################################
----- Decision Trees -----
[0 1 0 0 0 0 0 1 0 1 1 1 1]
Accuracy:  0.461538461538
##################################################



********** TESTCASE -  2 **********
----- RANDOM FOREST -----
[1 1 1 1 1 1 0 0 1 0 0 0 0]
Accuracy:  0.538461538462
######################################